# Specify all necessary information to find and connect to each hardware
# device that will be used on any of the scopes.
hardware:
  daq:
    type: NI
  camera:
    -
      type: HamamatsuOrca
      serial_number: 302158
    -
      type: HamamatsuOrca
      serial_number: 302352
  filter_wheel:
    type: SutterFilterWheel
    port: COM19
    baudrate: 9600
    number_of_wheels: 2
  stage:
    -
      type: PI
      controllername: 'C-884'
      stages: L-509.20DG10 L-509.40DG10 L-509.20DG10 M-060.DG M-406.4PD NOSTAGE
      refmode: FRF FRF FRF FRF FRF FRF
      serial_number: 119060508
    -
      type: Thorlabs
      serial_number: 7400375
  zoom:
    type: DynamixelZoom
    servo_id: 1
    port: COM18
    baudrate: 1000000
  lasers:
    type: Omicron
    wavelengths:
      -
        wavelength: 488
        port: COM19
      -
        wavelength: 561
        port: COM4
      -
        wavelength: 642
        port: COM17

# Only one microscope can be active in the GUI at a time, but all microscopes will be accessible
microscopes:
  -
    name: low
    daq:
      hardware:
        type: NI

      # NI PCIe-1073 Chassis with PXI-6259 and PXI-6733 DAQ Boards.
      # Sampling rate in Hz
      sample_rate: 100000
      sweep_time: 0.2

      # triggers
      master_trigger_out_line: PXI6259/port0/line1
      camera_trigger_out_line: /PXI6259/ctr0
      trigger_source: /PXI6259/PFI0

      # Galvos
      galvo_etl_task_line: PXI6259/ao0:3
      galvo_ao: PXI6259/ao0

      # Digital Laser Outputs
      laser_port_switcher: PXI6733/port0/line0
      laser_0_do: PXI6733/port0/line2
      laser_1_do: PXI6733/port0/line3
      laser_2_do: PXI6733/port0/line4

      # Analog Laser Outputs
      laser_0_ao: PXI6733/ao0
      laser_1_ao: PXI6733/ao1
      laser_2_ao: PXI6733/ao2

    camera:
      hardware:
        type: HamamatsuOrca
        serial_number: 302352
      x_pixels: 2048.0
      y_pixels: 2048.0
      pixel_size_in_microns: 6.5
      subsampling: [1, 2, 4]
      sensor_mode: Normal  # 12 for progressive, 1 for normal.
      readout_direction: Top-to-Bottom  # Top-to-Bottom', 'Bottom-to-Top'
      lightsheet_rolling_shutter_width: 608
      defect_correct_mode: 2.0
      binning: 1x1
      readout_speed: 1.0
      trigger_active: 1.0
      trigger_mode: 1.0 # external light-sheet mode
      trigger_polarity: 2.0  # positive pulse
      trigger_source: 2.0  # 2 = external, 3 = software.
      exposure_time: 20 # Use milliseconds throughout.
      delay_percent: 10
      pulse_percent: 1
      line_interval: 0.000075
      display_acquisition_subsampling: 4
      average_frame_rate: 4.969
      frames_to_average: 1
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
    remote_focus_device:
      hardware:
        type: NI
        channel: PXI6259/ao2
      # Optotune EL-16-40-TC-VIS-5D-1-C
      remote_focus_delay_percent: 7.5
      remote_focus_ramp_rising_percent: 85
      remote_focus_ramp_falling_percent: 2.5
      remote_focus_amplitude: 0.7
      remote_focus_offset: 2.3
      remote_focus_min_ao: 0
      remote_focus_max_ao: 5
    filter_wheel:
      hardware:
        type: SutterFilterWheel
        wheel_number: 1
      filter_wheel_delay: .030 # in seconds
      available_filters:
        Empty-Alignment: 0
        GFP - FF01-515/30-32: 1
        RFP - FF01-595/31-32: 2
        Far-Red - BLP01-647R/31-32: 3
        Blocked1: 4
        Blocked2: 5
        Blocked3: 6
        Blocked4: 7
        Blocked5: 8
        Blocked6: 9
    stage:
      hardware:
        type: PI
        serial_number: 119060508
        axes: [x, y, z, theta, f]
      y_unload_position: 10000
      y_load_position: 90000

      startfocus: 75000
      x_max: 33500
      x_min: 16000
      y_max: 100000
      y_min: 2000
      z_max: 50000
      z_min: 25000
      f_max: 100000
      f_min: -100000
      theta_max: 360
      theta_min: 0

      x_rot_position: 2000
      y_rot_position: 2000
      z_rot_position: 2000

      xy_step: 500
      z_step: 500
      theta_step: 30
      f_step: 500

      position:
        x_pos: 25250
        y_pos: 40000
        z_pos: 40000
        f_pos: 70000
        theta_pos: 0
      velocity: 1000

      x_offset: 0
      y_offset: 0
      z_offset: 0
      f_offset: 0
      theta_offset: 0
    zoom:
      hardware:
        type: DynamixelZoom
        servo_id: 1
      position:
        0.63x: 0
        1x: 627
        2x: 1711
        3x: 2301
        4x: 2710
        5x: 3079
        6x: 3383
      pixel_size:
        0.63x: 9.7
        1x: 6.38
        2x: 3.14
        3x: 2.12
        4x: 1.609
        5x: 1.255
        6x: 1.044
    shutter:
      hardware:
        type: NI
        channel: PXI6259/port0/line0
      shutter_min_do: 0
      shutter_max_do: 5
    lasers:
      # Omicron LightHub Ultra
      # 488 and 640 are LuxX+ Lasers
      # 561 is a Coherent OBIS Laser
      hardware:
        type: Omicron
      wavelengths:
        - wavelength: 488
          type: LuxX
          index: 0
        - wavelength: 561
          type: Obis
          index: 1
        - wavelength: 642
          type: LuxX
          index: 2

      min_ao: 0
      max_ao: 5
      min_do: 0
      max_do: 5
      delay_percent: 10
      pulse_percent: 87
  -
    name: high
    daq:
      hardware:
        type: NI

      # NI PCIe-1073 Chassis with PXI-6259 and PXI-6733 DAQ Boards.
      # Sampling rate in Hz
      sample_rate: 100000
      sweep_time: 0.2

      # triggers
      master_trigger_out_line: PXI6259/port0/line1
      camera_trigger_out_line: /PXI6259/ctr0
      trigger_source: /PXI6259/PFI0

      # Galvos
      galvo_etl_task_line: PXI6259/ao0:3
      galvo_ao: PXI6259/ao1

      # Digital Laser Outputs
      laser_port_switcher: PXI6733/port0/line0
      laser_0_do: PXI6733/port0/line2
      laser_1_do: PXI6733/port0/line3
      laser_2_do: PXI6733/port0/line4

      # Analog Laser Outputs
      laser_0_ao: PXI6733/ao0
      laser_1_ao: PXI6733/ao1
      laser_2_ao: PXI6733/ao2
    camera:
      hardware:
        type: HamamatsuOrca
        serial_number: 302158
      x_pixels: 2048.0
      y_pixels: 2048.0
      pixel_size_in_microns: 6.5
      subsampling: [1, 2, 4]
      sensor_mode: Normal  # 12 for progressive, 1 for normal.
      readout_direction: Top-to-Bottom  # Top-to-Bottom', 'Bottom-to-Top'
      lightsheet_rolling_shutter_width: 100
      defect_correct_mode: 2.0
      binning: 1x1
      readout_speed: 1.0
      trigger_active: 1.0
      trigger_mode: 1.0 # external light-sheet mode
      trigger_polarity: 2.0  # positive pulse
      trigger_source: 2.0  # 2 = external, 3 = software.
      exposure_time: 20 # Use milliseconds throughout.
      delay_percent: 10
      pulse_percent: 1
      line_interval: 0.000075
      display_acquisition_subsampling: 4
      average_frame_rate: 4.969
      frames_to_average: 1
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
    remote_focus_device:
      hardware:
        type: NI
        channel: PXI6259/ao3
      # Optotune EL-16-40-TC-VIS-5D-1-C
      remote_focus_delay_percent: 7.5
      remote_focus_ramp_rising_percent: 85
      remote_focus_ramp_falling_percent: 2.5
      remote_focus_amplitude: 0.7
      remote_focus_offset: 2.3
      remote_focus_min_ao: -0.7
      remote_focus_max_ao: 0.7
    filter_wheel:
      hardware:
        type: SutterFilterWheel
        wheel_number: 2
      filter_wheel_delay: .030 # in seconds
      available_filters:
        Empty-Alignment: 0
        GFP - FF01-515/30-32: 1
        RFP - FF01-595/31-32: 2
        Far-Red - BLP01-647R/31-32: 3
        Blocked1: 4
        Blocked2: 5
        Blocked3: 6
        Blocked4: 7
        Blocked5: 8
        Blocked6: 9
    stage:
      hardware:
        -
          type: PI
          serial_number: 119060508
          axes: [x, y, z, theta]
        -
          type: Thorlabs
          serial_number: 7400375
          axes: [f]
      y_unload_position: 10000
      y_load_position: 90000

      startfocus: 75000
      x_max: 33500
      x_min: 16000
      y_max: 100000
      y_min: 2000
      z_max: 50000
      z_min: 25000
      f_max: 100000
      f_min: -100000
      theta_max: 360
      theta_min: 0

      x_rot_position: 2000
      y_rot_position: 2000
      z_rot_position: 2000

      xy_step: 500
      z_step: 500
      theta_step: 30
      f_step: 500

      position:
        x_pos: 25250
        y_pos: 40000
        z_pos: 40000
        f_pos: 0
        theta_pos: 0
      velocity: 1000

      x_offset: 1500
      y_offset: 1720
      z_offset: -14311
      f_offset: 0
      theta_offset: 0
    zoom:
      position:
        N/A: 0
      pixel_size:
        N/A: 0.167
    shutter:
      hardware:
        type: NI
        channel: PXI6259/port0/line0
      shutter_min_do: 0
      shutter_max_do: 5
    lasers:
      # Omicron LightHub Ultra
      # 488 and 640 are LuxX+ Lasers
      # 561 is a Coherent OBIS Laser
      hardware:
        type: Omicron
      wavelengths:
        - wavelength: 488
          type: LuxX
          index: 0
        - wavelength: 561
          type: Obis
          index: 1
        - wavelength: 642
          type: LuxX
          index: 2

      min_ao: 0
      max_ao: 5
      min_do: 0
      max_do: 5
      delay_percent: 10
      pulse_percent: 87