microscopes:
  SpectralTIRF_lt538:
    daq:
      hardware:
        name: daq
        type: NI
      sample_rate: 100000
      sweep_time: 0.2
      master_trigger_out_line: PCIE6738/port0/line1
      camera_trigger_out_line: /PCIE6738/ctr0
      trigger_source: /PCIE6738/PFI0
      laser_port_switcher: PCIE6738/port0/line0
      laser_switch_state: False
    # dichroic:
    #   hardware:
    #     name: ASI
    #     type: ASI #synthetic #ASI
    #     port: COM17
    #     axes: [S]
    #     baudrate: 115200
    #   available_dichroics:
    #     510LP: 0
    #     570LP: 1
    #     640LP: 2
    camera:
      hardware:
        name: camera
        type: HamamatsuOrca
        serial_number: 003055
      x_pixels: 2048.0
      y_pixels: 2048.0
      pixel_size_in_microns: 6.5
      subsampling: [1, 2, 4]
      sensor_mode: Normal  # 12 for progressive, 1 for normal. Normal/Light-Sheet
      readout_direction: Top-to-Bottom  # Top-to-Bottom', 'Bottom-to-Top'
      lightsheet_rolling_shutter_width: 608
      defect_correct_mode: 2.0
      binning: 1x1
      readout_speed: 1.0
      trigger_active: 1.0
      trigger_mode: 1.0 # external light-sheet mode
      trigger_polarity: 2.0  # positive pulse
      trigger_source: 2.0  # 2 = external, 3 = software.
      exposure_time: 20 # Use milliseconds throughout.
      delay_percent: 10
      pulse_percent: 1
      line_interval: 0.000075
      display_acquisition_subsampling: 4
      average_frame_rate: 4.969
      frames_to_average: 1
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
      x_pixels_step: 4
      y_pixels_step: 4
      x_pixels_min: 4
      y_pixels_min: 4
    remote_focus_device:
      hardware:
        name: daq
        type: NI
        channel: PCIE6738/ao2
        min: 0
        max: 5
      delay_percent: 7.5
      ramp_rising_percent: 85
      ramp_falling_percent: 2.5
      amplitude: 0.7
      offset: 2.3
    galvo:
      -
        hardware:
          name: daq
          type: NI
          channel: PCIE6738/ao2  #galvo-x
          min: -5
          max: 5
        waveform: sine
        frequency: 99.9
        period: 10
        amplitude: 2.5
        offset: 0
        duty_cycle: 50
        phase: 0
      -
        hardware:
          name: daq
          type: NI
          channel: PCIE6738/ao3  #galvo-y
          min: -5
          max: 5
        waveform: sine
        frequency: 99.9
        period: 10
        amplitude: 2.5
        offset: 0
        duty_cycle: 50
        phase: 90
    filter_wheel:
      -
        hardware:
          name: emission
          type: ASI
          wheel_number: 0
          port: COM17
          baudrate: 115200
        filter_wheel_delay: .030 # in seconds
        available_filters:
          Empty 1: 0
          482/35: 1
          520/15: 2
          NF03-488E: 3
          Blocked2: 4
          Blocked3: 5
          Empty 2: 6
          Blocked 4: 7
          Blocked 5: 8
          Blocked 6: 9
      -
        hardware:
          name: emission
          type: ASI
          wheel_number: 1
          port: COM17
          baudrate: 115200
        filter_wheel_delay: .030 # in seconds
        available_filters:
          Empty 1: 0
          575/15: 1
          647/57: 2
          Blocked: 3
          593/lp: 4
          578/21: 5
          Empty 2: 6
          Blocked 4: 7
          Blocked 5: 8
          Blocked 6: 9
    stage:
      hardware:
        -
          name: ASI
          type: ASI
          port: COM17
          baudrate: 115200
          serial_number: 119060508
          axes: [x, y, z]
          axes_mapping: [X, Y, Z]
          volts_per_micron: None
          axes_channels: None
          max: None
          min: None
        -
          name: Synthetic
          type: SyntheticStage
          serial_number: 119060508
          axes: [theta, f]
          axes_mapping: [theta, f]
          volts_per_micron: None
          axes_channels: None
          max: None
          min: None

      x_max: 50000
      x_min: -50000
      y_max: 50000
      y_min: -50000
      z_max: 50000
      z_min: -50000
      f_max: 50000
      f_min: 0
      theta_max: 360
      theta_min: 0

      x_step: 500
      y_step: 500
      z_step: 500
      theta_step: 30
      f_step: 500
      velocity: 1000
    zoom:
      hardware:
        name: zoom
        type: synthetic
        servo_id: 1
      position:
        110x: 0
      pixel_size:
        110x: 0.059
    shutter:
      hardware:
        name: daq
        type: synthetic
        channel: PCIE6738/port0/line0
        min: 0
        max: 5
    lasers:
      - wavelength: 405
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/port1/line1 #38/35
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao21
            min: 0
            max: 5
        type: Obis
        index: 0
        delay_percent: 10
        pulse_percent: 87

      - wavelength: 445
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao4
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao5
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87

      - wavelength: 488
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao6
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao7
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87

      - wavelength: 514
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao8
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao9
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 532
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao10
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao11
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 562
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao12
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao13
            min: 0
            max: 5
        type: Obis
        index: 1
        delay_percent: 10
        pulse_percent: 87

      - wavelength: 592
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao14
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao15
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87


      - wavelength: 642
        onoff:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao16
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: NI
            channel: PCIE6738/ao17
            min: 0
            max: 5
        type: LuxX
        index: 2
        delay_percent: 10
        pulse_percent: 87


gui:
  channels:
    count: 5
    laser_power:
      min: 0
      max: 100
      step: 10
    exposure_time:
      min: 1
      max: 1000
      step: 5
    interval_time:
      min: 0
      max: 1000
      step: 5
  stack_acquisition:
    step_size:
      min: 0.200
      max: 1000
      step: 0.1
    start_pos:
      min: -5000
      max: 5000
      step: 1
    end_pos:
      min: -5000
      max: 10000
      step: 1
  timepoint:
    timepoints:
      min: 1
      max: 1000
      step: 1
    stack_pause:
      min: 0
      max: 1000
      step: 1