%YAML 1.2
---
Devices:
  daq: NI #NI or SyntheticDAQ
  camera: HamamatsuOrca # SyntheticCamera or HamamatsuOrca
  etl: ETL  #ETL or SyntheticETL
  filter_wheel: Sutter #Sutter or SyntheticFilterWheel
  stage: PI  # PI or SyntheticStage
  zoom: Dynamixel  #Dynamixel or SyntheticZoom

DAQParameters:
  # NI PCIe-1073 Chassis with PXI-6259 and PXI-6733 DAQ Boards.
  # Sampling rate in Hz
  samplerate: 100000

  # triggers
  master_trigger_out_line: PXI6259/port0/line1
  camera_trigger_out_line: PXI6259/ctr0
  trigger_source: PXI6259/PFI0
  galvo_etl_task_line: PXI625/ao0:3
  laser_task_line: PXI6733/ao0:7

  # Galvos
  galvo_l_ao: PXI6259/ao0
  galvo_r_ao: PXI6259/ao1

  # Remote Focusing Systems
  remote_focus_l_ao: PXI6259/ao2
  remote_focus_r_ao: PXI6259/ao3

  # Lasers
  laser_port_switcher: PXI6733/port0/line0
  laser_0_do: PXI6733/port0/line2
  laser_0_ao: PXI6733/port0/line5
  laser_1_do: PXI6733/port0/line3
  laser_1_ao: PXI6733/port0/line6
  laser_2_do: PXI6733/port0/line4
  laser_2_ao: PXI6733/port0/line7

  # shutters
  shutter_left: PXI6259/port0/line0
  shutter_right: PXI6259/port2/line0

CameraParameters:
  # Hamamatsu Orca Flash 4.0
  number_of_cameras: 1
  x_pixels: 2048
  y_pixels: 2048
  x_pixel_size_in_microns: 6.5
  y_pixel_size_in_microns: 6.5
  subsampling: [1, 2, 4]
  sensor_mode: 12  # 12 for progressive
  defect_correct_mode: 2
  binning: 1x1
  readout_speed: 1
  trigger_active: 1
  trigger_mode: 1 # external light-sheet mode
  trigger_polarity: 2  # positive pulse
  trigger_source: 2  # external
  exposure_time: .02
  delay_percent: 10
  pulse_percent: 1
  line_interval: 0.000075
  display_live_subsampling: 2
  display_acquisition_subsampling: 2
  average_frame_rate: 4.969

RemoteFocusParameters:
  # Remote Focusing Systems
  # remote_focus_l is an Optotune EL-16-40-TC-VIS-5D-1-C
  remote_focus_l_delay_percent: 7.5
  remote_focus_l_ramp_rising_percent: 85
  remote_focus_l_ramp_falling_percent: 2.5
  remote_focus_l_amplitude: 0.7
  remote_focus_l_offset: 2.3
  remote_focus_l_min_ao: 0
  remote_focus_l_min_ao: 5

  # remote_focus_r is a ThorLabs BLINK High-Speed Focuser
  remote_focus_r_delay_percent: 7.5
  remote_focus_r_ramp_rising_percent: 85
  remote_focus_r_ramp_falling_percent: 2.5
  remote_focus_r_amplitude: 0.7
  remote_focus_r_offset: 2.3
  remote_focus_r_min_ao: -10
  remote_focus_r_max_ao: 10

FilterWheelParameters:
  # Sutter Lambda 10-3 Filter Wheel Controller with 2x LB10-W32 10-position Filter Wheels
  filter_wheel_port: COM9
  baudrate: 9600
  number_of_filter_wheels: 2
  filter_wheel_delay: .030 # in seconds
  available_filters: {
    Empty-Alignment: 0,
    GFP - FF01-515/30-32: 1,
    RFP - FF01-595/31-32: 2,
    Far-Red - BLP01-647R/31-32: 3,
    Blocked1: 4,
    Blocked2: 5,
    Blocked3: 6,
    Blocked4: 7,
    Blocked5: 8,
    Blocked6: 9
  }

GalvoParameters:
  # Digitally Scanned Galvo for MesoSPIM Module
  # Thorlabs GVS211/M 10 mm system.
  galvo_l_frequency: 99.9
  galvo_l_amplitude: 2.5
  galvo_l_offset: 0
  galvo_l_duty_cycle: 50
  galvo_l_phase: np.pi / 2
  galvo_l_min_ao: -5
  galvo_l_max_ao: 5

  # Shadow Reduction Galvo for NanoSPIM Module
  # Cambridge Technology CRS 4 kHz system.
  galvo_r_amplitude: 0.5
  galvo_r_min_ao: -5
  galvo_r_max_ao: 5

LaserParameters:
  # Omicron LightHub Ultra
  # 488 and 640 are LuxX+ Lasers
  # 561 is a Coherent OBIS Laser
  number_of_lasers: 3

  laser_min_ao: 0
  laser_max_ao: 5
  laser_min_do: 0
  laser_max_do: 5

  laser_0_index: 0 # I did this, and it seems stupid.
  laser_1_index: 1
  laser_2_index: 2

  laser_0_wavelength: 488nm
  laser_1_wavelength: 562nm
  laser_2_wavelength: 642nm

  laser_l_delay_percent: 10
  laser_l_pulse_percent: 87
  laser_r_delay_percent: 10
  laser_r_pulse_percent: 87

StageParameters:
  # Physik Instrumente C-884 Controller with 5x Stages, listed below.
  controllername: 'C-884'
  stages: L-509.20DG10 L-509.40DG10 L-509.20DG10 M-060.DG M-406.4PD NOSTAGE
  refmode: FRF FRF FRF FRF FRF FRF
  serialnum: 119060508
  y_unload_position: 10000
  y_load_position: 90000
  startfocus: 70700
  x_max: 50000
  x_min: 2000
  y_max: 100000
  y_min: 2000
  z_max: 50000
  z_min: 2000
  f_max: 100000
  f_min: 2000
  theta_max: 360
  theta_min: 0
  x_rot_position: 2000
  y_rot_position: 2000
  z_rot_position: 2000
  xy_step: 500
  z_step: 500
  theta_step: 30
  f_step: 500
  position: {
    x_pos: 35000,
    y_pos: 42000,
    z_pos: 15500,
    f_pos: 70000,
    theta_pos: 0
  }
  velocity: 1000

ZoomParameters:
  # Robotis Dynamixel MX-28R Robot Servo
  servo_id: 1
  COMport: COM21
  baudrate: 1000000
  zoom_position: {
    0.63x: 0,
    1x: 627,
    2x: 1711,
    3x: 2301,
    4x: 2710,
    5x: 3079,
    6x: 3383
  }
  low_res_zoom_pixel_size: {
    0.63x: 9.7,
    1x: 6.38,
    2x: 3.14,
    3x: 2.12,
    4x: 1.609,
    5x: 1.255,
    6x: 1.044
  }
  high_res_zoom_pixel_size: 0.167

ShutterParameters:
  # 2x ThorLabs SHB1T 1" Shutters
  shutter_min_do: 0
  shutter_max_do: 5

GUIParameters:
  number_of_channels: 5